
name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Bump Version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: minor
          custom_release_rules: bug:patch:Fixes,chore:patch:Chores,docs:patch:Documentation,feat:minor:Features,refactor:minor:Refactors,test:patch:Tests,ci:patch:Development,dev:patch:Development
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.x
      - name: Build Artifacts
        run: build/build.sh "${{ steps.tag_version.outputs.new_tag }}"
      - name: Create Release
        uses: ncipollo/release-action@v1.16.0
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          artifacts: |
            dist/cbr_${{ steps.tag_version.outputs.new_tag }}_linux_amd64
            dist/cbr_${{ steps.tag_version.outputs.new_tag }}_linux_arm64
            dist/cbr_${{ steps.tag_version.outputs.new_tag }}_darwin_amd64
            dist/cbr_${{ steps.tag_version.outputs.new_tag }}_darwin_arm64
            dist/cbr_${{ steps.tag_version.outputs.new_tag }}_windows_amd64.exe
          artifactErrorsFailBuild: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
